### ISSUE TITLE
Incoming ride requests not working

### ISSUE THREAD

**Issue by miklo88** [Lambda-School-Labs/carpal-fe#115]
Incoming ride requests are not working. 
Data populates with request, displays briefly to the browser then within 10 milliseconds declinces the ride request and removes it. (See attached photo for reference.)
 
Error occuring on both staging and master branches. Ay dio mio.

**Comment by smv5047** [comment]
![Screen Shot 2020-05-24 at 5 27 10 PM](https://user-images.githubusercontent.com/38800900/82765474-42ae1d00-9de5-11ea-80c5-6fcdda602d28.png)

**Comment by miklo88** [comment]
Request status we're getting - 304

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/304
